name: Build & Deploy Update

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Disable SSR (Fix build error)
        run: |
          jq 'del(.projects.app.architect.build.options.server, .projects.app.architect.build.options.ssr, .projects.app.architect.build.options.outputMode, .projects.app.architect.build.options.prerender)' angular.json > angular.tmp.json
          mv angular.tmp.json angular.json
          rm -f src/main.server.ts src/app/app.config.server.ts src/server.ts || true

      - name: Build Angular
        run: npx ng build --configuration production --base-href ./

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel (AUTO CONFIRM)
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
